apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
  labels:
    app: {{  .Values.frontendLabel  }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontendService.ports.port }}
    targetPort: {{ .Values.frontendService.ports.targetPort }}
    protocol: TCP
  selector:
    app: {{  .Values.frontendLabel  }}
