global:
  kibanaEnabled: true
  storageClass: gp2-mongo

master:
  masterOnly: false
  replicaCount: 1
  heapSize: "1g"
  resources:
    requests:
      cpu: "250m" 
      memory: "1Gi"
    limits:
      cpu: "500m" 
      memory: "2Gi"
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  persistence:
    enabled: true
    storageClass: gp2-mongo
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 30Gi

data:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: gp2-mongo
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 30Gi

ingest:
  enabled: false

coordinating:
  replicaCount: 0

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: "gp2-mongo"

persistence:
  enabled: true
  storageClass: gp2-mongo

security:
  enabled: true
  elasticPassword: "9sRLSqZOhtUpSpyn"
  tls:
    restEncryption: true
    autoGenerated: true

kibana:
  ingress:
    enabled: false
  elasticsearch:
    security:
      tls:
        enabled: true
        verificationMode: "none"
        usePemCerts: false
      auth:
        enabled: true
        kibanaPassword: "9sRLSqZOhtUpSpyn"
        createSystemUser: true 
        elasticsearchPasswordSecret: "elasticsearch"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
