config:
  logLevel: info
  service: |
    [SERVICE]
        Daemon Off
        Flush 5
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        Trace_Error On

  ## Inputs for Fluent Bit
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/todo-app-backend*.log
        Parser docker
        Tag backend.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /var/log/containers/todo-app-frontend*.log
        Parser docker
        Tag frontend.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /var/log/containers/todo-app-mongodb*.log
        Parser mongodb_json_parser
        Tag mongodb.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /var/log/containers/ingress-controller-ingress-nginx-controller*.log
        Parser nginx_ingress
        Tag nginx.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## Filters for processing logs
  filters: |
    [FILTER]
        Name kubernetes
        Match backend.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size False
        K8S-Logging.Parser On

    [FILTER]
        Name kubernetes
        Match frontend.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size False
        K8S-Logging.Parser On

    [FILTER]
        Name parser
        Match mongodb.*
        Key_Name log
        Parser mongodb_json_parser
        Reserve_Data On

    [FILTER]
        Name modify
        Match mongodb.*
        Set log_level ERROR
        Condition Key_value_matches msg .*error.*

    [FILTER]
        Name modify
        Match mongodb.*
        Set log_level INFO
        Condition Key_value_does_not_match msg .*error.*

    [FILTER]
        Name kubernetes
        Match mongodb.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size False
        K8S-Logging.Parser On

    [FILTER]
        Name parser
        Match nginx.*
        Key_Name log
        Parser nginx_ingress
        Reserve_Data On

    [FILTER]
        Name modify
        Match nginx.*
        Condition Key_value_matches log ".*https://todoapp.ddns.net.*"
        Set website_access_log true

    [FILTER]
        Name kubernetes
        Match nginx.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size False
        K8S-Logging.Parser On

  ## Outputs for Fluent Bit
  outputs: |
    [OUTPUT]
        Name es
        Match backend.*
        Index logging-backend-logs
        Type _doc
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix backend-logs
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match frontend.*
        Index logging-frontend-logs
        Type _doc
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix frontend-logs
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match mongodb.*
        Index logging-mongo-logs
        Type _doc
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix mongo-logs
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match nginx.*
        Index logging-nginx-logs
        Type _doc
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix nginx-logs
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match host.*
        Index logging-host-logs
        Type _doc
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix node-logs
        Retry_Limit False
        Suppress_Type_Name On

  ## Custom parsers for Fluent Bit
  customParsers: |
    [PARSER]
        Name mongodb_json_parser
        Format json
        Time_Key t.$date
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name nginx_ingress
        Format regex
        Regex ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>[A-Z]+) (?<request>[^ ]*) (?<protocol>[^\"]*)" (?<status>[0-9]{3}) (?<body_bytes_sent>[0-9]+) "(?<http_referer>[^\"]*)" "(?<http_user_agent>[^\"]*)"
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
