apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-tools
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: todo-app
    server: https://kubernetes.default.svc
  source:
    repoURL: git@gitlab.com:bootcamp3554848/portfolio/gitops-config.git
    path: infra-apps/infra-tools
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
