FROM node:18-alpine

WORKDIR /app

# Copy the package files to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the E2E test files
COPY e2e.test.js /app/e2e.test.js

# Command to run the tests
CMD ["npm", "run", "test:e2e"]
