FROM python:3.9-slim

WORKDIR /app

# Copy application files and test files
COPY app.py /app/app.py
COPY tests/ /app/tests/
COPY requirements.txt /app/requirements.txt


# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run tests
CMD ["pytest", "-v"]
